a = input('digite algo:')
print('oque voce digitou pertence a classe', type(a))
print('so tem letras maisculas ?: ', a.isupper())
print('algo é um caractere ?: ', a.isalpha())
print('algo é alphanumerico ?: ', a.isalnum())
print('algo é um numero ?: ', a.isnumeric())
print('algo so te espaços ?: ', a.isspace())
print('algo so tem letras minusculas ?: ', a.islower())
print('algo esta capitalizado ?: ', a.istitle())
